version: '3.8'

services:

  wordpress:
    image: wordpress:php7.4-apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: example_db_wp
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db/sqls:/docker-entrypoint-initdb.d

  volumes:
    db:
    wordpress: